# Generated by Django 4.1.10 on 2023-11-25 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_car_make_remove_car_model_car_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='car',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.car'),
        ),
    ]
